apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - migrate-job.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
